export { default as DashboardLayout } from './DashboardLayout'
export { default as UploadFile } from './UploadFile'
export { default as Landing } from './Landing'
export { default as HomeLayout } from './HomeLayout'
export { default as Register } from './Register'
export { default as Login} from './Login'
export { default as Error} from './Error'
export { default as UploadedFiles} from './UploadedFiles'
export { default as Action} from './Action'
export { default as Profile} from './Profile'